// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/holidays": {
            "get": {
                "produces": [
                    "application/json",
                    "text/xml"
                ],
                "tags": [
                    "HolyDays"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "fromDate (YYYY-MM-DD)",
                        "name": "fromDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "toDate (YYYY-MM-DD)",
                        "name": "toDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "holiday type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "application/json or application/xml",
                        "name": "Accept",
                        "in": "header"
                    }
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1/",
	Schemes:          []string{},
	Title:            "Unicomer tech challenge",
	Description:      "Tech Challenge",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
