basePath: /api/v1/
host: localhost:8080
info:
  contact: {}
  description: Tech Challenge
  title: Unicomer tech challenge
  version: "1.0"
paths:
  /:
    get:
      parameters:
      - description: filter
        in: path
        name: filter
        required: true
        type: string
      - description: application/json or application/xml
        in: header
        name: Accept
        type: string
      responses: {}
      summary: Get
      tags:
      - HolyDays
swagger: "2.0"
