basePath: /api/v1/
definitions:
  http.ErrorResponse:
    properties:
      code:
        example: 404
        type: integer
      message:
        example: error
        type: string
    type: object
  http.HoliDay:
    properties:
      date:
        type: string
      extra:
        type: string
      inalienable:
        type: boolean
      title:
        type: string
      type:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Tech Challenge
  title: Unicomer tech challenge
  version: "1.0"
paths:
  /holidays:
    get:
      parameters:
      - description: fromDate (YYYY-MM-DD)
        in: query
        name: fromDate
        type: string
      - description: toDate (YYYY-MM-DD)
        in: query
        name: toDate
        type: string
      - description: holiday type
        in: query
        name: type
        type: string
      - description: application/json or application/xml
        in: header
        name: Accept
        type: string
      produces:
      - application/json
      - text/xml
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/http.HoliDay'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.ErrorResponse'
      summary: Get
      tags:
      - HoliDays
swagger: "2.0"
